language: python
python:
    - "2.7"
    - "3.5"
before_install:
    - pip install -U pip setuptools
    - pip install -U tox
install:
    - pip install -r test-requirements.pip
script: tox
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
