language: python
python:
    - "2.7"
    - "3.5"
install:
    - pip install -r test-requirements.pip
    - python setup.py develop
    - (cd demo; python setup.py develop)
script: flake8 chartjs && demo test demoproject
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
